# Generated by Django 4.2.21 on 2025-06-01 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(help_text='Unique table number.', unique=True)),
                ('capacity', models.IntegerField(help_text='Maximum number of guests this table can accommodate.')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField(help_text='The date of the reservation.')),
                ('booking_time', models.TimeField(help_text='The time of the reservation.')),
                ('number_of_guests', models.IntegerField(help_text='The number of guests for this reservation.')),
                ('notes', models.TextField(blank=True, help_text='Any special requests or notes from the customer.', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', help_text='Current status of the booking.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the booking was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the booking was last updated.')),
                ('table', models.ForeignKey(help_text='The table reserved. PROTECT prevents deleting a table with active bookings.', on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='bookings.table')),
                ('user', models.ForeignKey(help_text='The user who made the booking.', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['booking_date', 'booking_time'],
                'unique_together': {('table', 'booking_date', 'booking_time')},
            },
        ),
    ]
