# Generated by Django 4.2.21 on 2025-06-08 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when booking was created.'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='notes',
            field=models.TextField(blank=True, help_text='Optional special requests.', null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='number_of_guests',
            field=models.IntegerField(help_text='Number of guests for the reservation.'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='table',
            field=models.ForeignKey(help_text='The table reserved. Cannot be deleted if it has bookings.', on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='bookings.table'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when booking was last updated.'),
        ),
    ]
